#include <errno.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/inotify.h>
#include <unistd.h>
#include <fcntl.h>
#include <regex.h>        

#define LOG_PATH "/var/tmp/monitoring.log"

/* 
   Read all available inotify events from the file descriptor 'fd'.
   wd is the table of watch descriptors for the directories in argv.
   argc is the length of wd and argv.
   argv is the list of watched directories.
   Entry 0 of wd and argv is unused. 
*/


/* monitoring.c | module for generating a monitoring report
 * the report shows directory's content for addition/modification/deletion 
 * also shows if the directory itself was moved
 *
 * the report does not show anything related to hidden files since
 * they are generated by programs like vim and they are out of interest
 *
 * this function runs in a separate thread  = this was needed to read the same memory of the parent 
 * since this function needs to show the full path of each event using a lookup operation (wd -> path)
 *
 */


void handle_events(int fd)  {

	char buf[4096] __attribute__ ((aligned(__alignof__(struct inotify_event))));

// struct inotify_event {
// int      wd;       /* Watch descriptor */
// uint32_t mask;     /* Mask describing event */
// uint32_t cookie;   /* Unique cookie associating related events (for rename(2)) */
// uint32_t len;      /* Size of name field */
// char     name[];   /* Optional null-terminated name */
//};
	const struct inotify_event *event;
	int i;
	ssize_t len;
	char *ptr;
	regex_t regex;
	int reti;

           /* Loop while events can be read from inotify file descriptor. */

	for (;;) {

               /* Read some events. */

		len = read(fd, buf, sizeof buf);
		if (len == -1 && errno != EAGAIN) {
			perror("read");
			exit(EXIT_FAILURE);
		}

               /* If the nonblocking read() found no events to read, then
                  it returns -1 with errno set to EAGAIN. In that case,
                  we exit the loop. */

		if (len <= 0)
			break;

               /* Loop over all events in the buffer */

		for (ptr = buf; ptr < buf + len;
			ptr += sizeof(struct inotify_event) + event->len) {
		
		event = (const struct inotify_event *) ptr;

		// CHECK MODIFIED FILES INSIDE WATCHED DIRECTORY
		if ( event->len ) {

			reti = regcomp(&regex, "^[.]", 0);  // ignore hidden files

			if (reti) {
				printf("Could not compile regex\n"); fflush(stdout);
			}

			reti = regexec(&regex, event->name, 0, NULL, 0);

			if (!reti) { // HIDDEN FILE MATCHED 
				// printf("hidden file = ignoring\n"); fflush(stdout);
			}

			else if (reti == REG_NOMATCH) {
				if ( event->mask & IN_CREATE ) {
                                	if ( event->mask & IN_ISDIR ) {
	                                        printf("A %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                                else {
	                                        printf("A %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                        }
	                        else if ( event->mask & IN_DELETE ) {
	                                if ( event->mask & IN_ISDIR ) {
	                                        printf("D %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                                else {
	                                        printf("D %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                        }
	                        else if ( event->mask & IN_MODIFY ) {
	                                if ( event->mask & IN_ISDIR ) {
	                                        printf("M %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                                else {
	                                        printf("M %s\n", event->name );
	                                        fflush(stdout);
	                                }
	                        }

			}
			else {
				// regerror(reti, &regex, (const)event->name, event->len);
				printf("Regex match failed: %s\n", event->name); fflush(stderr);
			}

			regfree(&regex);
		}
	}
	}
}



// imonitord: init 
// -> fork(): handle_inotify_events(<params>);
int handle_inotify_events(int fd) {

	// redirect this child's output to LOG_PATH
	int out = open(LOG_PATH, O_RDWR|O_CREAT|O_APPEND, 0600);
	if (-1 == out) { perror(LOG_PATH); return 255; }

	if (-1 == dup2(out, fileno(stdout))) { perror("cannot redirect stdout"); return 255; }
        if (-1 == dup2(out, fileno(stderr))) { perror("cannot redirect stderr"); return 255; }

        int i, poll_num;
        nfds_t nfds;
        struct pollfd fds[2];

        nfds = 1;

        fds[0].fd = fd;
        fds[0].events = POLLIN;

        printf("\n\n\n\n\n");
	fflush(stdout);
        
	while (1) {
		poll_num = poll(fds, nfds, -1);
		if (poll_num == -1) {
			if (errno == EINTR)
				continue;
		perror("poll");
		exit(EXIT_FAILURE);
		}

		if (poll_num > 0) {
			if (fds[0].revents & POLLIN) {
				handle_events(fd);
			}
		}
           }

	fflush(stdout); close(out);
        fflush(stderr);

        exit(EXIT_SUCCESS);
}
